<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SmartStore.Web.Framework</AssemblyName>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <RestorePackages>true</RestorePackages>
    <RootNamespace>SmartStore.Web.Framework</RootNamespace>
    <SccAuxPath>
    </SccAuxPath>
    <SccLocalPath>
    </SccLocalPath>
    <SccProjectName>
    </SccProjectName>
    <SccProvider>
    </SccProvider>
    <SolutionDir>..\..\</SolutionDir>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.4.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
    <PackageReference Include="System.ComponentModel.EventBasedAsync" Version="4.3.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Cors" Version="5.2.7" />
    <PackageReference Include="System.Net.Requests" Version="4.3.0" />
    <PackageReference Include="System.Linq.Queryable" Version="4.3.0" />
    <PackageReference Include="System.Dynamic.Runtime" Version="4.3.0" />
    <PackageReference Include="Autofac" Version="8.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="BundleTransformer.SassAndScss" Version="1.13.9" />
    <PackageReference Include="LibSassHost" Version="1.5.0" />
    <PackageReference Include="JavaScriptEngineSwitcher.Core" Version="3.24.1" />
    <PackageReference Include="AutoprefixerHost" Version="3.1.0" />
    <PackageReference Include="FluentValidation" Version="11.10.0" />
    <PackageReference Include="System.Buffers" Version="4.6.0" />
    <PackageReference Include="AdvancedStringBuilder" Version="0.1.1" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.OData.Edm" Version="8.2.3" />
    <PackageReference Include="DotLiquid" Version="2.3.47" />
    <PackageReference Include="Microsoft.Spatial" Version="8.2.1" />
    <PackageReference Include="Microsoft.AspNet.OData" Version="7.7.1" />
    <PackageReference Include="Microsoft.OData.Core" Version="8.2.3" />
    <PackageReference Include="CommonServiceLocator" Version="2.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Libraries/SmartStore.Core/SmartStore.Core.csproj" />
    <ProjectReference Include="../../Libraries/SmartStore.Data/SmartStore.Data.csproj" />
    <ProjectReference Include="../../Libraries/SmartStore.Services/SmartStore.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Telerik.Web.Mvc">
      <HintPath>..\..\..\lib\Telerik\Telerik.Web.Mvc.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Theming/Assets/AutoPrefixPostProcessor.cs">
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\AssemblySharedInfo.cs">
      <Link>Properties\AssemblySharedInfo.cs</Link>
    </Compile>
    <Compile Include="..\..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config">
      <SubType>Designer</SubType>
    </None>
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>"SmartStore.Core.Tests"</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>"SmartStore.Services.Tests"</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>"SmartStore.Web.MVC.Tests"</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>