<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SmartStore.WebApi</AssemblyName>
    <DocumentationFile></DocumentationFile>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <RestorePackages>true</RestorePackages>
    <RootNamespace>SmartStore.WebApi</RootNamespace>
    <SccAuxPath></SccAuxPath>
    <SccLocalPath></SccLocalPath>
    <SccProjectName></SccProjectName>
    <SccProvider></SccProvider>
    <SolutionDir>..\..\</SolutionDir>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath Condition="'$(Configuration)' == 'Debug'">..\..\Presentation\SmartStore.Web\Plugins\SmartStore.WebApi\</OutputPath>
    <OutputPath Condition="'$(Configuration)' == 'Release'">..\..\Presentation\SmartStore.Web\Plugins\SmartStore.WebApi\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="*" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.4.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Cors" Version="5.2.7" />
    <PackageReference Include="Autofac" Version="8.4.0" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNet.OData" Version="7.7.1" />
    <PackageReference Include="Microsoft.OData.Core" Version="8.4.2" />
    <PackageReference Include="Microsoft.OData.Edm" Version="8.4.3" />
    <PackageReference Include="Microsoft.Spatial" Version="8.4.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Libraries/SmartStore.Core/SmartStore.Core.csproj" />
    <ProjectReference Include="../../Libraries/SmartStore.Services/SmartStore.Services.csproj" />
    <ProjectReference Include="../../Libraries/SmartStore.Data/SmartStore.Data.csproj" />
    <ProjectReference Include="../../Presentation/SmartStore.Web.Framework/SmartStore.Web.Framework.csproj" />
    <ProjectReference Include="../../Presentation/SmartStore.Web/SmartStore.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Telerik.Web.Mvc">
      <HintPath>..\..\..\lib\Telerik\Telerik.Web.Mvc.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemDefinitionGroup>
    <ProjectReference>
      <Private>False</Private>
    </ProjectReference>
  </ItemDefinitionGroup>
  <ItemGroup>
    <Compile Include="..\..\AssemblySharedInfo.cs">
      <Link>Properties\AssemblySharedInfo.cs</Link>
    </Compile>
    <Compile Include="..\..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Description.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Include="Views\WebApi\Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}" />
    </VisualStudio>
  </ProjectExtensions>
</Project>