<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SmartStore.Data.Tests</AssemblyName>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <PostBuildEvent>if not exist "$(TargetDir)x86" md "$(TargetDir)x86" 
xcopy /s /y "$(SolutionDir)packages\SqlServerCompact.4.0.8482.1\NativeBinaries\x86\*.*" "$(TargetDir)x86"
if not exist "$(TargetDir)amd64" md "$(TargetDir)amd64"
xcopy /s /y "$(SolutionDir)packages\SqlServerCompact.4.0.8482.1\NativeBinaries\amd64\*.*" "$(TargetDir)amd64"
    if not exist "$(TargetDir)x86" md "$(TargetDir)x86"
    xcopy /s /y "$(SolutionDir)packages\Microsoft.SqlServer.Compact.4.0.8876.1\NativeBinaries\x86\*.*" "$(TargetDir)x86"
    if not exist "$(TargetDir)amd64" md "$(TargetDir)amd64"
    xcopy /s /y "$(SolutionDir)packages\Microsoft.SqlServer.Compact.4.0.8876.1\NativeBinaries\amd64\*.*" "$(TargetDir)amd64"</PostBuildEvent>
    <Prefer32Bit>false</Prefer32Bit>
    <RestorePackages>true</RestorePackages>
    <RootNamespace>SmartStore.Data.Tests</RootNamespace>
    <SccAuxPath></SccAuxPath>
    <SccLocalPath></SccLocalPath>
    <SccProjectName></SccProjectName>
    <SccProvider></SccProvider>
    <SolutionDir>..\..\</SolutionDir>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="*" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Libraries/SmartStore.Core/SmartStore.Core.csproj" />
    <ProjectReference Include="../../Libraries/SmartStore.Data/SmartStore.Data.csproj" />
    <ProjectReference Include="../SmartStore.Tests/SmartStore.Tests.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
</Project>