<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SmartStore.PayPal</AssemblyName>
    <OutputType>Library</OutputType>
    <Prefer32Bit>false</Prefer32Bit>
    <RestorePackages>true</RestorePackages>
    <RootNamespace>SmartStore.PayPal</RootNamespace>
    <SolutionDir>..\..\</SolutionDir>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath Condition="'$(Configuration)' == 'Debug'">..\..\Presentation\SmartStore.Web\Plugins\SmartStore.PayPal\</OutputPath>
    <OutputPath Condition="'$(Configuration)' == 'Release'">..\..\Presentation\SmartStore.Web\Plugins\SmartStore.PayPal\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.4.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="Autofac" Version="8.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
    <PackageReference Include="FluentValidation" Version="11.10.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Libraries/SmartStore.Core/SmartStore.Core.csproj" />
    <ProjectReference Include="../../Libraries/SmartStore.Services/SmartStore.Services.csproj" />
    <ProjectReference Include="../../Presentation/SmartStore.Web.Framework/SmartStore.Web.Framework.csproj" />
    <ProjectReference Include="../../Presentation/SmartStore.Web/SmartStore.Web.csproj" />
  </ItemGroup>
  <ItemDefinitionGroup>
    <Reference>
      <Private>False</Private>
    </Reference>
    <ProjectReference>
      <Private>False</Private>
    </ProjectReference>
  </ItemDefinitionGroup>
  <ItemGroup>
    <Compile Include="..\..\AssemblySharedInfo.cs">
      <Link>Properties\AssemblySharedInfo.cs</Link>
    </Compile>
    <Compile Include="..\..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Content\checkout-button-de.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\favicon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\checkout-button-default.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\checkout-button-en.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\instalments-sm.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\instalments.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalExpress\Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\branding.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\smartstore.paypal.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="changelog.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="packages.config" />
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Content Include="Views\PayPalStandard\Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalStandard\PaymentInfo.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalDirect\Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalDirect\PaymentInfo.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalExpress\MiniShoppingCart.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalPlus\Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalPlus\PaymentWall.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalPlus\PaymentWallScripting.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalInstalments\Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\Shared\Partials\ApiConfiguration.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalInstalments\PaymentInfo.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalInstalments\OrderDetails.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalInstalments\OrderDetails.Print.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalInstalments\OrderSummaryTotals.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalInstalments\Promotion.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalInstalments\PromotionPopup.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\PayPalInstalments\Promotion.Content.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Include="Views\PayPalInstalments\OrderDetails.liquid">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Web References\PayPalSvc\PayPalSvc.wsdl" />
    <None Include="Web References\PayPalSvc\Reference.map">
      <Generator>MSDiscoCodeGenerator</Generator>
      <LastGenOutput>Reference.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Description.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <WebReferences Include="Web References\" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <ItemGroup>
    <WebReferenceUrl Include="https://www.paypalobjects.com/wsdl/PayPalSvc.wsdl">
      <UrlBehavior>Dynamic</UrlBehavior>
      <RelPath>Web References\PayPalSvc\</RelPath>
      <UpdateFromURL>https://www.paypalobjects.com/wsdl/PayPalSvc.wsdl</UpdateFromURL>
      <ServiceLocationURL></ServiceLocationURL>
      <CachedDynamicPropName></CachedDynamicPropName>
      <CachedAppSettingsObjectName>Settings</CachedAppSettingsObjectName>
      <CachedSettingsPropName>SmartStore_Plugin_Payments_PayPalExpress_PayPalSvc_PayPalAPIInterfaceService</CachedSettingsPropName>
    </WebReferenceUrl>
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}" />
    </VisualStudio>
  </ProjectExtensions>
</Project>