<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SmartStore.Clickatell</AssemblyName>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <RestorePackages>true</RestorePackages>
    <RootNamespace>SmartStore.Clickatell</RootNamespace>
    <SccAuxPath></SccAuxPath>
    <SccLocalPath></SccLocalPath>
    <SccProjectName></SccProjectName>
    <SccProvider></SccProvider>
    <SolutionDir>..\..\</SolutionDir>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath Condition="'$(Configuration)' == 'Debug'">..\..\Presentation\SmartStore.Web\Plugins\SmartStore.Clickatell\</OutputPath>
    <OutputPath Condition="'$(Configuration)' == 'Release'">..\..\Presentation\SmartStore.Web\Plugins\SmartStore.Clickatell\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Libraries/SmartStore.Core/SmartStore.Core.csproj" />
    <ProjectReference Include="../../Libraries/SmartStore.Services/SmartStore.Services.csproj" />
    <ProjectReference Include="../../Presentation/SmartStore.Web.Framework/SmartStore.Web.Framework.csproj" />
  </ItemGroup>
  <ItemDefinitionGroup>
    <ProjectReference>
      <Private>False</Private>
    </ProjectReference>
  </ItemDefinitionGroup>
  <ItemGroup>
    <Compile Include="..\..\AssemblySharedInfo.cs">
      <Link>Properties\AssemblySharedInfo.cs</Link>
    </Compile>
    <Compile Include="..\..\AssemblyVersionInfo.cs">
      <Link>Properties\AssemblyVersionInfo.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
    <Content Include="Content\branding.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\SmsClickatell\Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Description.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}" />
    </VisualStudio>
  </ProjectExtensions>
</Project>